apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "docker-build-access-key"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "SSH key to access docker-build agent"
type: Opaque
stringData:
  username: vagrant
# cat .vagrant/machines/docker-build/virtualbox/private_key
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAt8KPt5OJLWQ+FFITuLSIJb6USlShnuCWBi0wqLXuOC8ZErgb
    RV49nlKPxzgmcVtXbmawTHrYddlJQhUraU4gInZUcsZBoj7IwmAx/CUsKhRc7fi6
    2OXvCf0SsZWE4cbXIKcu9S/ERj/1M8l5a3ySPH/LKeR1ujkSxNJqQrhGtxIFg44j
    rdTY0O2nh8jIpl2i8PN+GWNoR66Jg9FP9yYOTm70BNsuuw28N61YHwJ1VtZV3IUT
    3oR22jGRBf16U+OiUh6TtYEtIPq3WVrWXkkNd4nSjOrhaJqDiYaCrAR5aQceucXi
    xSDH5LCxNBlkcXG5SA+yAKY4aAL0lNI7NOLfBQIDAQABAoIBAQCZVELPDs/7jBUw
    p3vFNv4TYH4jt5JUG1mTNcnQPF3Vi5cEQ5KdwxDvNjy6ImQRWgIOIKkiZ66ORwwV
    k8xxRbsShmHYkwzY8EJbziBnIC1Fv0/7UPu3V8SpNP2QKA6ExYFjwZwxAfZoF53l
    5EroIT10Nb2z6ulAxbaffGMl4NVAkuMIUlT/k6zAkbGThip7HyidG4eRKUdwdTt7
    +4yFTsS5aaIemU2jFYah1F7oecMr6Yqm/YjkpU9bvwDJw2tlkKtLzTZ8yfdrAr5Y
    xmxUG4RcfjvxWoJlrb6i6FosTBJzX8BBimQgmj/BY79F1G57IA2fy+F7iXNvCeOU
    Sg/SuI2BAoGBANpGBNKR1lcQUPFysjI9+2HXAwMwe+m7Q00TyyvY6SVHOkjm6nV9
    1khF2gCWfHCS4UM8FRoyEdXjlgANWh38SmFglAdhhs+H3sINNRgsDqyhqC439EQY
    Mfw1AcKKwXhiVT5umG/XJurAS49LiSBlOUAxNvXZKMDe3G2qINvH9HU5AoGBANeF
    axGLjySlj4l4zd2w032CaOcCqr7ARHSNk+laRqz0fNb4vCP5ZVKw0HkywZ/YLYTZ
    9ku4QN/W6aGryV5cJhFD+Dul5q8Rv81lJIoSDtHm0Ory3cQ+fLHfPmlVO+TiSBiT
    yJ8giw/Q185T9QvkJ4ECzZGEtkRbHcnes2A6IGQtAoGBAJsDZQNiXRWB2epPaWwz
    BqdqepI2SZopytcfeofOSW2XEzaY/+OnFZpIOVV3ijKsrVwBfH8ZFf+P3IR29wwa
    k3xqiVZglcwnEzU/Cfj7uQQy3mzMgiYmBMG3p2NRBauIMj/fbVToOJQ5MrA2ldEy
    8iC7kuuwaLfoziT30NQlQmBJAoGATCtRDeBe9Lq2ogVZ7LHj7QW8AXkF02isSO0I
    i35mYBYAURGTnLs1viXTaCIyIEYMwFkwHM6/ztxrscG+52R158A36QzXHKSPPw4x
    /cIoDrMevwqaqhLTiyG1MxD2nAwFIvqH+wVLYImU28z8W/mEpKnS8U0QBdSWEJRu
    nOGuNPkCgYAT4bqNCgWMZ1MZN4Kdu5HJ03UEwUiJMppGgdl7I+SwsNuszIvevomi
    IcC3YEX3TcRCtYakSz7hREyiWj4ROx2ObRrPC/xPbQ1ZITB9a8bwg9jwoXZ3l1uT
    xnBF4UNvkM/fMPKwkqSa/QiM4/2MTXaRqp9EkHNBkZS+vf2ugYAgbg==
    -----END RSA PRIVATE KEY-----
